"""add action_plans table

Revision ID: 1a94db3c36f7
Revises: ed7f8910aaf2
Create Date: 2026-04-08 16:58:04.231218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a94db3c36f7'
down_revision: Union[str, Sequence[str], None] = 'ed7f8910aaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('reason_not_met', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tracking_id'], ['indicator_trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_plans')
    # ### end Alembic commands ###
