"""add_direccion_linea_fields

Revision ID: 7a605faf66b0
Revises: 3f8e7d1c2345
Create Date: 2026-05-06 22:30:51.227809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a605faf66b0'
down_revision: Union[str, Sequence[str], None] = '3f8e7d1c2345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidences', 'tracking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'evidences', 'users', ['user_id'], ['id'])
    op.add_column('indicator_assignments', sa.Column('direccion_at_assignment', sa.String(), nullable=True))
    op.add_column('indicator_assignments', sa.Column('linea_at_assignment', sa.String(), nullable=True))
    op.add_column('indicator_assignments', sa.Column('numero_linea_at_assignment', sa.String(), nullable=True))
    op.alter_column('indicator_assignments', 'start_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('indicator_assignments', 'end_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('12'))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linea', sa.String(), nullable=True))
    op.add_column('users', sa.Column('numero_linea', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numero_linea')
    op.drop_column('users', 'linea')
    op.drop_column('users', 'direccion')
    op.alter_column('indicator_assignments', 'end_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('12'))
    op.alter_column('indicator_assignments', 'start_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('indicator_assignments', 'numero_linea_at_assignment')
    op.drop_column('indicator_assignments', 'linea_at_assignment')
    op.drop_column('indicator_assignments', 'direccion_at_assignment')
    op.drop_constraint(None, 'evidences', type_='foreignkey')
    op.alter_column('evidences', 'tracking_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
