"""add_month_indicator

Revision ID: 91cdc669197d
Revises: 7a605faf66b0
Create Date: 2026-05-07 14:04:57.537981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cdc669197d'
down_revision: Union[str, Sequence[str], None] = '7a605faf66b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_assignments', sa.Column('month', sa.Integer(), nullable=True))
    op.drop_column('indicator_assignments', 'start_month')
    op.drop_column('indicator_assignments', 'end_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_assignments', sa.Column('end_month', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=True))
    op.add_column('indicator_assignments', sa.Column('start_month', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('indicator_assignments', 'month')
    # ### end Alembic commands ###
