"""fix user typing

Revision ID: 9412f8d0d9e8
Revises: 2fb2c4824439
Create Date: 2026-03-05 20:04:21.701865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9412f8d0d9e8"
down_revision: Union[str, Sequence[str], None] = "2fb2c4824439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_roles", ["user_id", "role_id"])
    op.alter_column("users", "position_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "position_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(None, "user_roles", type_="unique") # type: ignore
    # ### end Alembic commands ###
