"""add achieved_total

Revision ID: b3baea75c882
Revises: 1a94db3c36f7
Create Date: 2026-04-08 17:27:33.161661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3baea75c882'
down_revision: Union[str, Sequence[str], None] = '1a94db3c36f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_trackings', sa.Column('achieved_total', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator_trackings', 'achieved_total')
    # ### end Alembic commands ###
