"""add formula frequency

Revision ID: ed7f8910aaf2
Revises: 4f6faf9c744f
Create Date: 2026-04-08 14:51:17.379151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7f8910aaf2'
down_revision: Union[str, Sequence[str], None] = '4f6faf9c744f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_assignments', sa.Column('formula', sa.Text(), nullable=True))
    op.add_column('indicator_assignments', sa.Column('frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator_assignments', 'frequency')
    op.drop_column('indicator_assignments', 'formula')
    # ### end Alembic commands ###
